
version: 0.2

phases: 
  pre_build:
    commands:
      #install dependencies
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      #build
      - echo Building...
      - npm run build
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build