
version: 0.2

phases:
  pre-build:
    commands:
      - echo Installing app dependencies...
      - npm install
  build:
    commands:
      - echo Building static site...
      - npm run build

artifacts:
  files:
    - '**/*'
    discard-paths: no
    base-directory: build